{-# LANGUAGE TemplateHaskell #-}

module AbsLatte where

-- Haskell module generated by the BNF converter

import Control.Lens


newtype Ident = Ident String deriving (Eq, Ord, Show, Read)
data Program = Program [TopDef]
  deriving (Eq, Ord, Show, Read)

data TopDef = FnDef Type Ident [Arg] Block
  deriving (Eq, Ord, Show, Read)
data Arg = Arg Type Ident
  deriving (Eq, Ord, Show, Read)

data Block = Block [Stmt]
  deriving (Eq, Ord, Show, Read)

data Stmt
    = Empty
    | BStmt Block
    | Decl { _st :: Type,  _items :: [Item] }
    | Ass {_sid :: Ident, _se :: Expr}
    | Incr {_sid :: Ident}
    | Decr {_sid :: Ident}
    | Ret {_se :: Expr}
    | VRet
    | Cond {_se :: Expr, _ss :: Stmt}
    | CondElse {_se :: Expr, _ss1 :: Stmt, _ss2 :: Stmt}
    | While {_se :: Expr, _ss :: Stmt}
    | SExp {_se :: Expr}
  deriving (Eq, Ord, Show, Read)

data Item = NoInit {_iid :: Ident} | Init { _iid :: Ident, e :: Expr}
  deriving (Eq, Ord, Show, Read)

data Type = Int | Str | Bool | Void | Fun Type [Type]
  deriving (Eq, Ord, Show, Read)

data Expr
    = EVar Ident
    | ELitInt Integer
    | ELitTrue
    | ELitFalse
    | EApp {_eid :: Ident, _ees :: [Expr]}
    | EString String
    | Neg Expr
    | Not Expr
    | EMul {_ee1 :: Expr, _emop :: MulOp, _ee2 :: Expr}
    | EAdd {_ee1 :: Expr, _eaop :: AddOp, _ee2 :: Expr}
    | ERel {_ee1 :: Expr, _erop :: RelOp, _ee2 :: Expr}
    | EAnd {_ee1 :: Expr, _ee2 :: Expr}
    | EOr  {_ee1 :: Expr, _ee2 :: Expr}
  deriving (Eq, Ord, Show, Read)

data AddOp = Plus | Minus
  deriving (Eq, Ord, Show, Read)

data MulOp = Times | Div | Mod
  deriving (Eq, Ord, Show, Read)

data RelOp = LTH | LE | GTH | GE | EQU | NE
  deriving (Eq, Ord, Show, Read)


makeLenses ''Item
makeLenses ''Stmt
makeLenses ''Expr
